### ISSUE TITLE
check internet in openstack.sh script

### ISSUE THREAD

**Issue by kenmlee** [mustafatoraman/openstack#1]
Hi, Mustafa, 

This is Ming Zhe Li a cloud advisor from IBM China. I'm using your OpenStackLab@MAC to build my OpenStack Env.

In **check_internet_access** function of **openstack.sh**, could you please change:

```
wget -q -T 10 --spider http://google.com
```

to

```
wget -q -T 10 --spider http://ibm.com
```

You know we have some problem when try to access google.com.

Thank you for your great work.

**Comment by mustafatoraman** [comment]
Hi Ming,

Thanks for reporting the issue , I didn't think about that. I made the change and this should be resolved now.

Thank you!

**Comment by mustafatoraman** [comment]
closing the issue #1
